/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.course.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedGroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CourseRegister service. Represents a row in the &quot;COURSE_CourseRegister&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.course.model.impl.CourseRegisterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.course.model.impl.CourseRegisterImpl}.
 * </p>
 *
 * @author ces
 * @see CourseRegister
 * @see com.liferay.course.model.impl.CourseRegisterImpl
 * @see com.liferay.course.model.impl.CourseRegisterModelImpl
 * @generated
 */
public interface CourseRegisterModel extends BaseModel<CourseRegister>,
	StagedGroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a course register model instance should use the {@link CourseRegister} interface instead.
	 */

	/**
	 * Returns the primary key of this course register.
	 *
	 * @return the primary key of this course register
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this course register.
	 *
	 * @param primaryKey the primary key of this course register
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this course register.
	 *
	 * @return the uuid of this course register
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this course register.
	 *
	 * @param uuid the uuid of this course register
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the course register ID of this course register.
	 *
	 * @return the course register ID of this course register
	 */
	public long getCourseRegisterId();

	/**
	 * Sets the course register ID of this course register.
	 *
	 * @param courseRegisterId the course register ID of this course register
	 */
	public void setCourseRegisterId(long courseRegisterId);

	/**
	 * Returns the group ID of this course register.
	 *
	 * @return the group ID of this course register
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this course register.
	 *
	 * @param groupId the group ID of this course register
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this course register.
	 *
	 * @return the company ID of this course register
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this course register.
	 *
	 * @param companyId the company ID of this course register
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this course register.
	 *
	 * @return the user ID of this course register
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this course register.
	 *
	 * @param userId the user ID of this course register
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this course register.
	 *
	 * @return the user uuid of this course register
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this course register.
	 *
	 * @param userUuid the user uuid of this course register
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this course register.
	 *
	 * @return the user name of this course register
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this course register.
	 *
	 * @param userName the user name of this course register
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this course register.
	 *
	 * @return the create date of this course register
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this course register.
	 *
	 * @param createDate the create date of this course register
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this course register.
	 *
	 * @return the modified date of this course register
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this course register.
	 *
	 * @param modifiedDate the modified date of this course register
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the course ID of this course register.
	 *
	 * @return the course ID of this course register
	 */
	public long getCourseId();

	/**
	 * Sets the course ID of this course register.
	 *
	 * @param courseId the course ID of this course register
	 */
	public void setCourseId(long courseId);

	/**
	 * Returns the status of this course register.
	 *
	 * @return the status of this course register
	 */
	public int getStatus();

	/**
	 * Sets the status of this course register.
	 *
	 * @param status the status of this course register
	 */
	public void setStatus(int status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CourseRegister courseRegister);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CourseRegister> toCacheModel();

	@Override
	public CourseRegister toEscapedModel();

	@Override
	public CourseRegister toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}